title:             OneAction NZ
email:             your-email@example.com
description:       A Blog Theme by Start Bootstrap
author:            OneAction NZ
baseurl:           ""
#url:              "http://blackrockdigital.github.io"
url:               "https://oneaction.nz"

# set timezone
timezone:           "Pacific/Auckland"

# Social Profiles
twitter_username:  OneActionNZ
github_username:   OneActionNZ
facebook_username: OneActionNZ

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
