title:             OneAction NZ
email:             your-email@example.com
description:       A Blog Theme by Start Bootstrap
author:            OneAction NZ
baseurl:           ""
#url:              "http://blackrockdigital.github.io"
url:               "https://oneaction.nz"

# Social Profiles
twitter_username:  SBootstrap
github_username:   BlackrockDigital
facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
