title:             OneAction NZ
email:             info@team.oneaction.nz
description:       Democracy Co-operative
author:            OneAction NZ
baseurl:           ""
#url:              "http://blackrockdigital.github.io"
url:               "https://oneaction.nz"

# set timezone
timezone:           "Pacific/Auckland"

# Social Profiles
twitter_username:  OneActionNZ
github_username:   OneActionNZ
facebook_username: OneActionNZ

# Build settings
future:            true #Build posts set in the future
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
